var UserProfile = {
    "tagName":"form",
    "name":"json" ,
    "method":"POST",
    "onSubmit":"return Submit();",
    "childNodes":[
           {
             "tagName":"label",
             "innerText":"Name",
             "for":"Name"
           },
           {
             "tagName":"input",
             "type":"text",
             "maxLength":40,
             "required":"",
             "name":"Name",
           },
           {
            "tagName":"label",
            "innerText":"Gender",
            "for":"Gender"
          },
           {
             "tagName":"select",
             "required":"",
             "name":"Gender",
             "childNodes":[
                 {
                    "tagName":"option",
                    "value":"Male",
                    "innerText":"Male"
                 },
                 {
                    "tagName":"option",
                    "value":"Female",
                    "innerText":"Female"
                 },
                 {
                    "tagName":"option",
                    "value":"Others",
                    "innerText":"Others"
                 }
             ]
           },
           {
            "tagName":"label",
            "innerText":"Address ",
          },
          {
            "tagName":"label",
            "innerText":" Street",
            "for":"Street"
          },
          {
            "tagName":"input",
            "type":"text",
            "required":"",
            "name":"Street",
          },
          {
            "tagName":"label",
            "innerText":"City",
            "for":"City"
          },
          {
            "tagName":"input",
            "type":"text",
            "required":"",
            "name":"City",
          },
          {
            "tagName":"label",
            "innerText":"State",
            "for":"State"
          },
          {
            "tagName":"input",
            "type":"text",
            "required":"",
            "name":"State",
          },
          {
            "tagName":"label",
            "innerText":"Country",
            "for":"Country"
          },
          {
            "tagName":"input",
            "type":"text",
            "required":"",
            "name":"Country",
          },
           {
               "tagName":"input",
                "type":"submit",
                "value":"submit",
          }
     ]
   }